package com.ankamagames.dofus.network
{
   import com.ankamagames.dofus.network.types.common.AbstractPlayerSearchInformation;
   import com.ankamagames.dofus.network.types.common.PlayerSearchCharacterNameInformation;
   import com.ankamagames.dofus.network.types.common.PlayerSearchTagInformation;
   import com.ankamagames.dofus.network.types.common.basic.StatisticData;
   import com.ankamagames.dofus.network.types.common.basic.StatisticDataBoolean;
   import com.ankamagames.dofus.network.types.common.basic.StatisticDataByte;
   import com.ankamagames.dofus.network.types.common.basic.StatisticDataInt;
   import com.ankamagames.dofus.network.types.common.basic.StatisticDataShort;
   import com.ankamagames.dofus.network.types.common.basic.StatisticDataString;
   import com.ankamagames.dofus.network.types.game.achievement.AchievementAchieved;
   import com.ankamagames.dofus.network.types.game.achievement.AchievementAchievedRewardable;
   import com.ankamagames.dofus.network.types.game.actions.fight.AbstractFightDispellableEffect;
   import com.ankamagames.dofus.network.types.game.actions.fight.FightTemporaryBoostEffect;
   import com.ankamagames.dofus.network.types.game.actions.fight.FightTemporaryBoostStateEffect;
   import com.ankamagames.dofus.network.types.game.actions.fight.FightTemporaryBoostWeaponDamagesEffect;
   import com.ankamagames.dofus.network.types.game.actions.fight.FightTemporarySpellBoostEffect;
   import com.ankamagames.dofus.network.types.game.actions.fight.FightTemporarySpellImmunityEffect;
   import com.ankamagames.dofus.network.types.game.actions.fight.FightTriggeredEffect;
   import com.ankamagames.dofus.network.types.game.approach.ServerSessionConstant;
   import com.ankamagames.dofus.network.types.game.approach.ServerSessionConstantInteger;
   import com.ankamagames.dofus.network.types.game.approach.ServerSessionConstantLong;
   import com.ankamagames.dofus.network.types.game.approach.ServerSessionConstantString;
   import com.ankamagames.dofus.network.types.game.character.CharacterMinimalAllianceInformations;
   import com.ankamagames.dofus.network.types.game.character.CharacterMinimalGuildInformations;
   import com.ankamagames.dofus.network.types.game.character.CharacterMinimalPlusLookAndGradeInformations;
   import com.ankamagames.dofus.network.types.game.character.CharacterMinimalPlusLookInformations;
   import com.ankamagames.dofus.network.types.game.character.characteristic.CharacterCharacteristic;
   import com.ankamagames.dofus.network.types.game.character.characteristic.CharacterCharacteristicDetailed;
   import com.ankamagames.dofus.network.types.game.character.characteristic.CharacterCharacteristicValue;
   import com.ankamagames.dofus.network.types.game.character.choice.CharacterBaseInformations;
   import com.ankamagames.dofus.network.types.game.character.choice.CharacterHardcoreOrEpicInformations;
   import com.ankamagames.dofus.network.types.game.character.debt.DebtInformation;
   import com.ankamagames.dofus.network.types.game.character.debt.KamaDebtInformation;
   import com.ankamagames.dofus.network.types.game.character.status.PlayerStatus;
   import com.ankamagames.dofus.network.types.game.character.status.PlayerStatusExtended;
   import com.ankamagames.dofus.network.types.game.context.EntityDispositionInformations;
   import com.ankamagames.dofus.network.types.game.context.FightEntityDispositionInformations;
   import com.ankamagames.dofus.network.types.game.context.GameContextActorInformations;
   import com.ankamagames.dofus.network.types.game.context.GameContextActorPositionInformations;
   import com.ankamagames.dofus.network.types.game.context.GameRolePlayTaxCollectorInformations;
   import com.ankamagames.dofus.network.types.game.context.IdentifiedEntityDispositionInformations;
   import com.ankamagames.dofus.network.types.game.context.MapCoordinates;
   import com.ankamagames.dofus.network.types.game.context.MapCoordinatesAndId;
   import com.ankamagames.dofus.network.types.game.context.MapCoordinatesExtended;
   import com.ankamagames.dofus.network.types.game.context.TaxCollectorStaticExtendedInformations;
   import com.ankamagames.dofus.network.types.game.context.TaxCollectorStaticInformations;
   import com.ankamagames.dofus.network.types.game.context.fight.BaseSpawnMonsterInformation;
   import com.ankamagames.dofus.network.types.game.context.fight.FightAllianceTeamInformations;
   import com.ankamagames.dofus.network.types.game.context.fight.FightResultAdditionalData;
   import com.ankamagames.dofus.network.types.game.context.fight.FightResultExperienceData;
   import com.ankamagames.dofus.network.types.game.context.fight.FightResultFighterListEntry;
   import com.ankamagames.dofus.network.types.game.context.fight.FightResultListEntry;
   import com.ankamagames.dofus.network.types.game.context.fight.FightResultMutantListEntry;
   import com.ankamagames.dofus.network.types.game.context.fight.FightResultPlayerListEntry;
   import com.ankamagames.dofus.network.types.game.context.fight.FightResultPvpData;
   import com.ankamagames.dofus.network.types.game.context.fight.FightResultTaxCollectorListEntry;
   import com.ankamagames.dofus.network.types.game.context.fight.FightTeamInformations;
   import com.ankamagames.dofus.network.types.game.context.fight.FightTeamMemberCharacterInformations;
   import com.ankamagames.dofus.network.types.game.context.fight.FightTeamMemberEntityInformation;
   import com.ankamagames.dofus.network.types.game.context.fight.FightTeamMemberInformations;
   import com.ankamagames.dofus.network.types.game.context.fight.FightTeamMemberMonsterInformations;
   import com.ankamagames.dofus.network.types.game.context.fight.FightTeamMemberTaxCollectorInformations;
   import com.ankamagames.dofus.network.types.game.context.fight.FightTeamMemberWithAllianceCharacterInformations;
   import com.ankamagames.dofus.network.types.game.context.fight.GameContextBasicSpawnInformation;
   import com.ankamagames.dofus.network.types.game.context.fight.GameContextSummonsInformation;
   import com.ankamagames.dofus.network.types.game.context.fight.GameFightAIInformations;
   import com.ankamagames.dofus.network.types.game.context.fight.GameFightCharacterInformations;
   import com.ankamagames.dofus.network.types.game.context.fight.GameFightCharacteristics;
   import com.ankamagames.dofus.network.types.game.context.fight.GameFightEntityInformation;
   import com.ankamagames.dofus.network.types.game.context.fight.GameFightFighterEntityLightInformation;
   import com.ankamagames.dofus.network.types.game.context.fight.GameFightFighterInformations;
   import com.ankamagames.dofus.network.types.game.context.fight.GameFightFighterLightInformations;
   import com.ankamagames.dofus.network.types.game.context.fight.GameFightFighterMonsterLightInformations;
   import com.ankamagames.dofus.network.types.game.context.fight.GameFightFighterNamedInformations;
   import com.ankamagames.dofus.network.types.game.context.fight.GameFightFighterNamedLightInformations;
   import com.ankamagames.dofus.network.types.game.context.fight.GameFightFighterTaxCollectorLightInformations;
   import com.ankamagames.dofus.network.types.game.context.fight.GameFightMonsterInformations;
   import com.ankamagames.dofus.network.types.game.context.fight.GameFightMonsterWithAlignmentInformations;
   import com.ankamagames.dofus.network.types.game.context.fight.GameFightMutantInformations;
   import com.ankamagames.dofus.network.types.game.context.fight.GameFightTaxCollectorInformations;
   import com.ankamagames.dofus.network.types.game.context.fight.SpawnCharacterInformation;
   import com.ankamagames.dofus.network.types.game.context.fight.SpawnCompanionInformation;
   import com.ankamagames.dofus.network.types.game.context.fight.SpawnInformation;
   import com.ankamagames.dofus.network.types.game.context.fight.SpawnMonsterInformation;
   import com.ankamagames.dofus.network.types.game.context.fight.SpawnScaledMonsterInformation;
   import com.ankamagames.dofus.network.types.game.context.roleplay.AllianceInformations;
   import com.ankamagames.dofus.network.types.game.context.roleplay.BasicAllianceInformations;
   import com.ankamagames.dofus.network.types.game.context.roleplay.BasicGuildInformations;
   import com.ankamagames.dofus.network.types.game.context.roleplay.BasicNamedAllianceInformations;
   import com.ankamagames.dofus.network.types.game.context.roleplay.GameRolePlayActorInformations;
   import com.ankamagames.dofus.network.types.game.context.roleplay.GameRolePlayCharacterInformations;
   import com.ankamagames.dofus.network.types.game.context.roleplay.GameRolePlayGroupMonsterInformations;
   import com.ankamagames.dofus.network.types.game.context.roleplay.GameRolePlayGroupMonsterWaveInformations;
   import com.ankamagames.dofus.network.types.game.context.roleplay.GameRolePlayHumanoidInformations;
   import com.ankamagames.dofus.network.types.game.context.roleplay.GameRolePlayMerchantInformations;
   import com.ankamagames.dofus.network.types.game.context.roleplay.GameRolePlayMountInformations;
   import com.ankamagames.dofus.network.types.game.context.roleplay.GameRolePlayMutantInformations;
   import com.ankamagames.dofus.network.types.game.context.roleplay.GameRolePlayNamedActorInformations;
   import com.ankamagames.dofus.network.types.game.context.roleplay.GameRolePlayNpcInformations;
   import com.ankamagames.dofus.network.types.game.context.roleplay.GameRolePlayNpcWithQuestInformations;
   import com.ankamagames.dofus.network.types.game.context.roleplay.GameRolePlayPortalInformations;
   import com.ankamagames.dofus.network.types.game.context.roleplay.GameRolePlayPrismInformations;
   import com.ankamagames.dofus.network.types.game.context.roleplay.GameRolePlayTreasureHintInformations;
   import com.ankamagames.dofus.network.types.game.context.roleplay.GroupMonsterStaticInformations;
   import com.ankamagames.dofus.network.types.game.context.roleplay.GroupMonsterStaticInformationsWithAlternatives;
   import com.ankamagames.dofus.network.types.game.context.roleplay.GuildInAllianceInformations;
   import com.ankamagames.dofus.network.types.game.context.roleplay.GuildInformations;
   import com.ankamagames.dofus.network.types.game.context.roleplay.HumanInformations;
   import com.ankamagames.dofus.network.types.game.context.roleplay.HumanOption;
   import com.ankamagames.dofus.network.types.game.context.roleplay.HumanOptionAlliance;
   import com.ankamagames.dofus.network.types.game.context.roleplay.HumanOptionEmote;
   import com.ankamagames.dofus.network.types.game.context.roleplay.HumanOptionFollowers;
   import com.ankamagames.dofus.network.types.game.context.roleplay.HumanOptionGuild;
   import com.ankamagames.dofus.network.types.game.context.roleplay.HumanOptionObjectUse;
   import com.ankamagames.dofus.network.types.game.context.roleplay.HumanOptionOrnament;
   import com.ankamagames.dofus.network.types.game.context.roleplay.HumanOptionSkillUse;
   import com.ankamagames.dofus.network.types.game.context.roleplay.HumanOptionTitle;
   import com.ankamagames.dofus.network.types.game.context.roleplay.breach.BreachBranch;
   import com.ankamagames.dofus.network.types.game.context.roleplay.breach.ExtendedBreachBranch;
   import com.ankamagames.dofus.network.types.game.context.roleplay.breach.ExtendedLockedBreachBranch;
   import com.ankamagames.dofus.network.types.game.context.roleplay.party.PartyInvitationMemberInformations;
   import com.ankamagames.dofus.network.types.game.context.roleplay.party.PartyMemberArenaInformations;
   import com.ankamagames.dofus.network.types.game.context.roleplay.party.PartyMemberInformations;
   import com.ankamagames.dofus.network.types.game.context.roleplay.party.entity.PartyEntityBaseInformation;
   import com.ankamagames.dofus.network.types.game.context.roleplay.party.entity.PartyEntityMemberInformation;
   import com.ankamagames.dofus.network.types.game.context.roleplay.quest.QuestActiveDetailedInformations;
   import com.ankamagames.dofus.network.types.game.context.roleplay.quest.QuestActiveInformations;
   import com.ankamagames.dofus.network.types.game.context.roleplay.quest.QuestObjectiveInformations;
   import com.ankamagames.dofus.network.types.game.context.roleplay.quest.QuestObjectiveInformationsWithCompletion;
   import com.ankamagames.dofus.network.types.game.context.roleplay.treasureHunt.PortalInformation;
   import com.ankamagames.dofus.network.types.game.context.roleplay.treasureHunt.TreasureHuntStep;
   import com.ankamagames.dofus.network.types.game.context.roleplay.treasureHunt.TreasureHuntStepDig;
   import com.ankamagames.dofus.network.types.game.context.roleplay.treasureHunt.TreasureHuntStepFight;
   import com.ankamagames.dofus.network.types.game.context.roleplay.treasureHunt.TreasureHuntStepFollowDirection;
   import com.ankamagames.dofus.network.types.game.context.roleplay.treasureHunt.TreasureHuntStepFollowDirectionToHint;
   import com.ankamagames.dofus.network.types.game.context.roleplay.treasureHunt.TreasureHuntStepFollowDirectionToPOI;
   import com.ankamagames.dofus.network.types.game.data.items.effects.ObjectEffect;
   import com.ankamagames.dofus.network.types.game.data.items.effects.ObjectEffectCreature;
   import com.ankamagames.dofus.network.types.game.data.items.effects.ObjectEffectDate;
   import com.ankamagames.dofus.network.types.game.data.items.effects.ObjectEffectDice;
   import com.ankamagames.dofus.network.types.game.data.items.effects.ObjectEffectDuration;
   import com.ankamagames.dofus.network.types.game.data.items.effects.ObjectEffectInteger;
   import com.ankamagames.dofus.network.types.game.data.items.effects.ObjectEffectLadder;
   import com.ankamagames.dofus.network.types.game.data.items.effects.ObjectEffectMinMax;
   import com.ankamagames.dofus.network.types.game.data.items.effects.ObjectEffectMount;
   import com.ankamagames.dofus.network.types.game.data.items.effects.ObjectEffectString;
   import com.ankamagames.dofus.network.types.game.friend.AcquaintanceInformation;
   import com.ankamagames.dofus.network.types.game.friend.AcquaintanceOnlineInformation;
   import com.ankamagames.dofus.network.types.game.friend.FriendInformations;
   import com.ankamagames.dofus.network.types.game.friend.FriendOnlineInformations;
   import com.ankamagames.dofus.network.types.game.friend.FriendSpouseInformations;
   import com.ankamagames.dofus.network.types.game.friend.FriendSpouseOnlineInformations;
   import com.ankamagames.dofus.network.types.game.friend.IgnoredInformations;
   import com.ankamagames.dofus.network.types.game.friend.IgnoredOnlineInformations;
   import com.ankamagames.dofus.network.types.game.guild.tax.TaxCollectorComplementaryInformations;
   import com.ankamagames.dofus.network.types.game.guild.tax.TaxCollectorGuildInformations;
   import com.ankamagames.dofus.network.types.game.guild.tax.TaxCollectorInformations;
   import com.ankamagames.dofus.network.types.game.guild.tax.TaxCollectorLootInformations;
   import com.ankamagames.dofus.network.types.game.guild.tax.TaxCollectorWaitingForHelpInformations;
   import com.ankamagames.dofus.network.types.game.house.AccountHouseInformations;
   import com.ankamagames.dofus.network.types.game.house.HouseGuildedInformations;
   import com.ankamagames.dofus.network.types.game.house.HouseInformations;
   import com.ankamagames.dofus.network.types.game.house.HouseInformationsForGuild;
   import com.ankamagames.dofus.network.types.game.house.HouseInformationsInside;
   import com.ankamagames.dofus.network.types.game.house.HouseInstanceInformations;
   import com.ankamagames.dofus.network.types.game.house.HouseOnMapInformations;
   import com.ankamagames.dofus.network.types.game.idol.Idol;
   import com.ankamagames.dofus.network.types.game.idol.PartyIdol;
   import com.ankamagames.dofus.network.types.game.interactive.InteractiveElement;
   import com.ankamagames.dofus.network.types.game.interactive.InteractiveElementNamedSkill;
   import com.ankamagames.dofus.network.types.game.interactive.InteractiveElementSkill;
   import com.ankamagames.dofus.network.types.game.interactive.InteractiveElementWithAgeBonus;
   import com.ankamagames.dofus.network.types.game.interactive.skill.SkillActionDescription;
   import com.ankamagames.dofus.network.types.game.interactive.skill.SkillActionDescriptionCollect;
   import com.ankamagames.dofus.network.types.game.interactive.skill.SkillActionDescriptionCraft;
   import com.ankamagames.dofus.network.types.game.interactive.skill.SkillActionDescriptionTimed;
   import com.ankamagames.dofus.network.types.game.mount.UpdateMountBooleanCharacteristic;
   import com.ankamagames.dofus.network.types.game.mount.UpdateMountCharacteristic;
   import com.ankamagames.dofus.network.types.game.mount.UpdateMountIntegerCharacteristic;
   import com.ankamagames.dofus.network.types.game.paddock.PaddockBuyableInformations;
   import com.ankamagames.dofus.network.types.game.paddock.PaddockGuildedInformations;
   import com.ankamagames.dofus.network.types.game.presets.EntitiesPreset;
   import com.ankamagames.dofus.network.types.game.presets.ForgettableSpellsPreset;
   import com.ankamagames.dofus.network.types.game.presets.FullStatsPreset;
   import com.ankamagames.dofus.network.types.game.presets.IconNamedPreset;
   import com.ankamagames.dofus.network.types.game.presets.IdolsPreset;
   import com.ankamagames.dofus.network.types.game.presets.ItemsPreset;
   import com.ankamagames.dofus.network.types.game.presets.Preset;
   import com.ankamagames.dofus.network.types.game.presets.PresetsContainerPreset;
   import com.ankamagames.dofus.network.types.game.presets.SpellsPreset;
   import com.ankamagames.dofus.network.types.game.presets.StatsPreset;
   import com.ankamagames.dofus.network.types.game.prism.AllianceInsiderPrismInformation;
   import com.ankamagames.dofus.network.types.game.prism.AlliancePrismInformation;
   import com.ankamagames.dofus.network.types.game.prism.PrismGeolocalizedInformation;
   import com.ankamagames.dofus.network.types.game.prism.PrismInformation;
   import com.ankamagames.dofus.network.types.game.prism.PrismSubareaEmptyInfo;
   import com.ankamagames.dofus.network.types.game.shortcut.Shortcut;
   import com.ankamagames.dofus.network.types.game.shortcut.ShortcutEmote;
   import com.ankamagames.dofus.network.types.game.shortcut.ShortcutEntitiesPreset;
   import com.ankamagames.dofus.network.types.game.shortcut.ShortcutObject;
   import com.ankamagames.dofus.network.types.game.shortcut.ShortcutObjectIdolsPreset;
   import com.ankamagames.dofus.network.types.game.shortcut.ShortcutObjectItem;
   import com.ankamagames.dofus.network.types.game.shortcut.ShortcutObjectPreset;
   import com.ankamagames.dofus.network.types.game.shortcut.ShortcutSmiley;
   import com.ankamagames.dofus.network.types.game.shortcut.ShortcutSpell;
   import com.ankamagames.dofus.network.types.game.social.AbstractSocialGroupInfos;
   import com.ankamagames.dofus.network.types.game.social.AllianceFactSheetInformations;
   import com.ankamagames.dofus.network.types.game.social.AlliancedGuildFactSheetInformations;
   import com.ankamagames.dofus.network.types.game.social.GuildFactSheetInformations;
   import com.ankamagames.dofus.network.types.game.social.GuildInAllianceVersatileInformations;
   import com.ankamagames.dofus.network.types.game.social.GuildInsiderFactSheetInformations;
   import com.ankamagames.dofus.network.types.game.social.GuildVersatileInformations;
   import com.ankamagames.jerakine.managers.StoreDataManager;
   import flash.utils.Dictionary;
   
   public class ProtocolTypeManager
   {
      
      private static const _typesTypes:Dictionary = new Dictionary();
      
      {
         _typesTypes[1956] = CharacterMinimalPlusLookInformations;
         _typesTypes[7196] = CharacterBaseInformations;
         _typesTypes[3956] = PartyMemberInformations;
         _typesTypes[358] = PartyMemberArenaInformations;
         _typesTypes[6670] = PartyInvitationMemberInformations;
         _typesTypes[9632] = CharacterHardcoreOrEpicInformations;
         _typesTypes[2440] = CharacterMinimalGuildInformations;
         _typesTypes[5854] = CharacterMinimalAllianceInformations;
         _typesTypes[889] = CharacterMinimalPlusLookAndGradeInformations;
         _typesTypes[7196] = CharacterBaseInformations;
         _typesTypes[3956] = PartyMemberInformations;
         _typesTypes[358] = PartyMemberArenaInformations;
         _typesTypes[6670] = PartyInvitationMemberInformations;
         _typesTypes[9632] = CharacterHardcoreOrEpicInformations;
         _typesTypes[2799] = EntityDispositionInformations;
         _typesTypes[9489] = IdentifiedEntityDispositionInformations;
         _typesTypes[2973] = FightEntityDispositionInformations;
         _typesTypes[6558] = AbstractSocialGroupInfos;
         _typesTypes[5973] = BasicGuildInformations;
         _typesTypes[6465] = GuildInformations;
         _typesTypes[8504] = GuildFactSheetInformations;
         _typesTypes[473] = GuildInsiderFactSheetInformations;
         _typesTypes[3579] = GuildInAllianceInformations;
         _typesTypes[1184] = AlliancedGuildFactSheetInformations;
         _typesTypes[3126] = BasicAllianceInformations;
         _typesTypes[56] = BasicNamedAllianceInformations;
         _typesTypes[1398] = AllianceInformations;
         _typesTypes[7735] = AllianceFactSheetInformations;
         _typesTypes[9761] = GuildVersatileInformations;
         _typesTypes[2686] = GuildInAllianceVersatileInformations;
         _typesTypes[8504] = GuildFactSheetInformations;
         _typesTypes[473] = GuildInsiderFactSheetInformations;
         _typesTypes[7735] = AllianceFactSheetInformations;
         _typesTypes[4789] = PrismSubareaEmptyInfo;
         _typesTypes[3408] = PrismGeolocalizedInformation;
         _typesTypes[1753] = PrismInformation;
         _typesTypes[4043] = AlliancePrismInformation;
         _typesTypes[9390] = AllianceInsiderPrismInformation;
         _typesTypes[2983] = CharacterCharacteristic;
         _typesTypes[651] = CharacterCharacteristicDetailed;
         _typesTypes[4252] = CharacterCharacteristicValue;
         _typesTypes[7292] = FightTeamMemberInformations;
         _typesTypes[3311] = FightTeamMemberCharacterInformations;
         _typesTypes[3733] = FightTeamMemberWithAllianceCharacterInformations;
         _typesTypes[9221] = FightTeamMemberTaxCollectorInformations;
         _typesTypes[8655] = FightTeamMemberMonsterInformations;
         _typesTypes[4737] = FightTeamMemberEntityInformation;
         _typesTypes[4316] = FightTeamInformations;
         _typesTypes[2474] = FightAllianceTeamInformations;
         _typesTypes[6094] = GameFightCharacteristics;
         _typesTypes[4588] = FightResultListEntry;
         _typesTypes[2947] = FightResultFighterListEntry;
         _typesTypes[7131] = FightResultTaxCollectorListEntry;
         _typesTypes[7134] = FightResultPlayerListEntry;
         _typesTypes[2372] = FightResultMutantListEntry;
         _typesTypes[2515] = FightResultAdditionalData;
         _typesTypes[4466] = FightResultPvpData;
         _typesTypes[9775] = FightResultExperienceData;
         _typesTypes[1188] = AbstractFightDispellableEffect;
         _typesTypes[320] = FightTemporaryBoostEffect;
         _typesTypes[3474] = FightTemporaryBoostStateEffect;
         _typesTypes[8477] = FightTemporarySpellBoostEffect;
         _typesTypes[7744] = FightTemporaryBoostWeaponDamagesEffect;
         _typesTypes[2214] = FightTemporarySpellImmunityEffect;
         _typesTypes[977] = FightTriggeredEffect;
         _typesTypes[2671] = ObjectEffect;
         _typesTypes[624] = ObjectEffectInteger;
         _typesTypes[222] = ObjectEffectCreature;
         _typesTypes[2694] = ObjectEffectLadder;
         _typesTypes[6930] = ObjectEffectMinMax;
         _typesTypes[1342] = ObjectEffectDuration;
         _typesTypes[3066] = ObjectEffectString;
         _typesTypes[7506] = ObjectEffectDice;
         _typesTypes[6498] = ObjectEffectDate;
         _typesTypes[5871] = ObjectEffectMount;
         _typesTypes[5898] = UpdateMountCharacteristic;
         _typesTypes[1327] = UpdateMountBooleanCharacteristic;
         _typesTypes[4747] = UpdateMountIntegerCharacteristic;
         _typesTypes[3614] = Shortcut;
         _typesTypes[2748] = ShortcutObject;
         _typesTypes[3086] = ShortcutObjectPreset;
         _typesTypes[8219] = ShortcutObjectIdolsPreset;
         _typesTypes[3792] = ShortcutObjectItem;
         _typesTypes[8389] = ShortcutSpell;
         _typesTypes[6309] = ShortcutSmiley;
         _typesTypes[2084] = ShortcutEmote;
         _typesTypes[5484] = ShortcutEntitiesPreset;
         _typesTypes[5210] = Idol;
         _typesTypes[1785] = PartyIdol;
         _typesTypes[1785] = PartyIdol;
         _typesTypes[8790] = AchievementAchieved;
         _typesTypes[676] = AchievementAchievedRewardable;
         _typesTypes[4223] = IgnoredInformations;
         _typesTypes[2860] = IgnoredOnlineInformations;
         _typesTypes[9750] = FriendInformations;
         _typesTypes[6842] = FriendOnlineInformations;
         _typesTypes[1] = AcquaintanceInformation;
         _typesTypes[6947] = AcquaintanceOnlineInformation;
         _typesTypes[9186] = FriendSpouseInformations;
         _typesTypes[6899] = FriendSpouseOnlineInformations;
         _typesTypes[4345] = InteractiveElementSkill;
         _typesTypes[8215] = InteractiveElementNamedSkill;
         _typesTypes[8429] = InteractiveElement;
         _typesTypes[7651] = InteractiveElementWithAgeBonus;
         _typesTypes[3956] = PartyMemberInformations;
         _typesTypes[358] = PartyMemberArenaInformations;
         _typesTypes[6670] = PartyInvitationMemberInformations;
         _typesTypes[8446] = PartyEntityBaseInformation;
         _typesTypes[3958] = PartyEntityMemberInformation;
         _typesTypes[9402] = SkillActionDescription;
         _typesTypes[4668] = SkillActionDescriptionTimed;
         _typesTypes[9547] = SkillActionDescriptionCollect;
         _typesTypes[4065] = SkillActionDescriptionCraft;
         _typesTypes[3662] = HouseInformations;
         _typesTypes[5019] = AccountHouseInformations;
         _typesTypes[261] = HouseInformationsInside;
         _typesTypes[9540] = HouseInformationsForGuild;
         _typesTypes[2155] = HouseOnMapInformations;
         _typesTypes[4670] = HouseInstanceInformations;
         _typesTypes[7631] = HouseGuildedInformations;
         _typesTypes[4586] = PaddockBuyableInformations;
         _typesTypes[5746] = PaddockGuildedInformations;
         _typesTypes[8832] = GameContextActorPositionInformations;
         _typesTypes[3338] = GameContextActorInformations;
         _typesTypes[8684] = GameFightFighterInformations;
         _typesTypes[3226] = GameFightAIInformations;
         _typesTypes[975] = GameFightMonsterInformations;
         _typesTypes[9829] = GameFightMonsterWithAlignmentInformations;
         _typesTypes[8023] = GameFightTaxCollectorInformations;
         _typesTypes[3910] = GameFightFighterNamedInformations;
         _typesTypes[5141] = GameFightCharacterInformations;
         _typesTypes[3991] = GameFightMutantInformations;
         _typesTypes[3550] = GameFightEntityInformation;
         _typesTypes[5720] = GameRolePlayActorInformations;
         _typesTypes[4623] = GameRolePlayNamedActorInformations;
         _typesTypes[1484] = GameRolePlayHumanoidInformations;
         _typesTypes[5654] = GameRolePlayMutantInformations;
         _typesTypes[8148] = GameRolePlayCharacterInformations;
         _typesTypes[2326] = GameRolePlayMountInformations;
         _typesTypes[2992] = GameRolePlayMerchantInformations;
         _typesTypes[5203] = GameRolePlayNpcInformations;
         _typesTypes[7842] = GameRolePlayNpcWithQuestInformations;
         _typesTypes[475] = GameRolePlayGroupMonsterInformations;
         _typesTypes[5020] = GameRolePlayGroupMonsterWaveInformations;
         _typesTypes[3649] = GameRolePlayTreasureHintInformations;
         _typesTypes[1656] = GameRolePlayTaxCollectorInformations;
         _typesTypes[7793] = GameRolePlayPrismInformations;
         _typesTypes[4028] = GameRolePlayPortalInformations;
         _typesTypes[3338] = GameContextActorInformations;
         _typesTypes[8684] = GameFightFighterInformations;
         _typesTypes[3226] = GameFightAIInformations;
         _typesTypes[975] = GameFightMonsterInformations;
         _typesTypes[9829] = GameFightMonsterWithAlignmentInformations;
         _typesTypes[8023] = GameFightTaxCollectorInformations;
         _typesTypes[3910] = GameFightFighterNamedInformations;
         _typesTypes[5141] = GameFightCharacterInformations;
         _typesTypes[3991] = GameFightMutantInformations;
         _typesTypes[3550] = GameFightEntityInformation;
         _typesTypes[5720] = GameRolePlayActorInformations;
         _typesTypes[4623] = GameRolePlayNamedActorInformations;
         _typesTypes[1484] = GameRolePlayHumanoidInformations;
         _typesTypes[5654] = GameRolePlayMutantInformations;
         _typesTypes[8148] = GameRolePlayCharacterInformations;
         _typesTypes[2326] = GameRolePlayMountInformations;
         _typesTypes[2992] = GameRolePlayMerchantInformations;
         _typesTypes[5203] = GameRolePlayNpcInformations;
         _typesTypes[7842] = GameRolePlayNpcWithQuestInformations;
         _typesTypes[475] = GameRolePlayGroupMonsterInformations;
         _typesTypes[5020] = GameRolePlayGroupMonsterWaveInformations;
         _typesTypes[3649] = GameRolePlayTreasureHintInformations;
         _typesTypes[1656] = GameRolePlayTaxCollectorInformations;
         _typesTypes[7793] = GameRolePlayPrismInformations;
         _typesTypes[4028] = GameRolePlayPortalInformations;
         _typesTypes[5720] = GameRolePlayActorInformations;
         _typesTypes[4623] = GameRolePlayNamedActorInformations;
         _typesTypes[1484] = GameRolePlayHumanoidInformations;
         _typesTypes[5654] = GameRolePlayMutantInformations;
         _typesTypes[8148] = GameRolePlayCharacterInformations;
         _typesTypes[2326] = GameRolePlayMountInformations;
         _typesTypes[2992] = GameRolePlayMerchantInformations;
         _typesTypes[5203] = GameRolePlayNpcInformations;
         _typesTypes[7842] = GameRolePlayNpcWithQuestInformations;
         _typesTypes[475] = GameRolePlayGroupMonsterInformations;
         _typesTypes[5020] = GameRolePlayGroupMonsterWaveInformations;
         _typesTypes[3649] = GameRolePlayTreasureHintInformations;
         _typesTypes[1656] = GameRolePlayTaxCollectorInformations;
         _typesTypes[7793] = GameRolePlayPrismInformations;
         _typesTypes[4028] = GameRolePlayPortalInformations;
         _typesTypes[4572] = HumanInformations;
         _typesTypes[3247] = HumanOption;
         _typesTypes[8293] = HumanOptionObjectUse;
         _typesTypes[1332] = HumanOptionAlliance;
         _typesTypes[7748] = HumanOptionGuild;
         _typesTypes[6314] = HumanOptionOrnament;
         _typesTypes[5644] = HumanOptionEmote;
         _typesTypes[5299] = HumanOptionTitle;
         _typesTypes[1691] = HumanOptionSkillUse;
         _typesTypes[2314] = HumanOptionFollowers;
         _typesTypes[1042] = TaxCollectorStaticInformations;
         _typesTypes[6146] = TaxCollectorStaticExtendedInformations;
         _typesTypes[6718] = TaxCollectorInformations;
         _typesTypes[1676] = TaxCollectorComplementaryInformations;
         _typesTypes[8602] = TaxCollectorGuildInformations;
         _typesTypes[9341] = TaxCollectorLootInformations;
         _typesTypes[9165] = TaxCollectorWaitingForHelpInformations;
         _typesTypes[954] = GroupMonsterStaticInformations;
         _typesTypes[822] = GroupMonsterStaticInformationsWithAlternatives;
         _typesTypes[3840] = QuestActiveInformations;
         _typesTypes[109] = QuestActiveDetailedInformations;
         _typesTypes[1560] = QuestObjectiveInformations;
         _typesTypes[9237] = QuestObjectiveInformationsWithCompletion;
         _typesTypes[9403] = SpawnInformation;
         _typesTypes[5895] = BaseSpawnMonsterInformation;
         _typesTypes[9707] = SpawnScaledMonsterInformation;
         _typesTypes[3997] = SpawnMonsterInformation;
         _typesTypes[5438] = SpawnCharacterInformation;
         _typesTypes[1867] = SpawnCompanionInformation;
         _typesTypes[3043] = GameContextBasicSpawnInformation;
         _typesTypes[9597] = GameContextSummonsInformation;
         _typesTypes[8684] = GameFightFighterInformations;
         _typesTypes[3226] = GameFightAIInformations;
         _typesTypes[975] = GameFightMonsterInformations;
         _typesTypes[9829] = GameFightMonsterWithAlignmentInformations;
         _typesTypes[8023] = GameFightTaxCollectorInformations;
         _typesTypes[3910] = GameFightFighterNamedInformations;
         _typesTypes[5141] = GameFightCharacterInformations;
         _typesTypes[3991] = GameFightMutantInformations;
         _typesTypes[3550] = GameFightEntityInformation;
         _typesTypes[1156] = GameFightFighterLightInformations;
         _typesTypes[7050] = GameFightFighterMonsterLightInformations;
         _typesTypes[4418] = GameFightFighterNamedLightInformations;
         _typesTypes[4311] = GameFightFighterTaxCollectorLightInformations;
         _typesTypes[5084] = GameFightFighterEntityLightInformation;
         _typesTypes[4951] = MapCoordinates;
         _typesTypes[992] = MapCoordinatesAndId;
         _typesTypes[1133] = MapCoordinatesExtended;
         _typesTypes[6748] = Preset;
         _typesTypes[4064] = PresetsContainerPreset;
         _typesTypes[7031] = IconNamedPreset;
         _typesTypes[3330] = SpellsPreset;
         _typesTypes[8969] = ForgettableSpellsPreset;
         _typesTypes[4860] = StatsPreset;
         _typesTypes[5155] = IdolsPreset;
         _typesTypes[8645] = EntitiesPreset;
         _typesTypes[3276] = FullStatsPreset;
         _typesTypes[5347] = ItemsPreset;
         _typesTypes[9693] = TreasureHuntStep;
         _typesTypes[6674] = TreasureHuntStepFollowDirectionToPOI;
         _typesTypes[1976] = TreasureHuntStepDig;
         _typesTypes[7124] = TreasureHuntStepFight;
         _typesTypes[9304] = TreasureHuntStepFollowDirectionToHint;
         _typesTypes[3436] = TreasureHuntStepFollowDirection;
         _typesTypes[8949] = AbstractPlayerSearchInformation;
         _typesTypes[7105] = PlayerSearchTagInformation;
         _typesTypes[1326] = PlayerSearchCharacterNameInformation;
         _typesTypes[2566] = PortalInformation;
         _typesTypes[9905] = BreachBranch;
         _typesTypes[5225] = ExtendedBreachBranch;
         _typesTypes[1195] = ExtendedLockedBreachBranch;
         _typesTypes[5225] = ExtendedBreachBranch;
         _typesTypes[1195] = ExtendedLockedBreachBranch;
         _typesTypes[223] = PlayerStatus;
         _typesTypes[4104] = PlayerStatusExtended;
         _typesTypes[2772] = ServerSessionConstant;
         _typesTypes[9726] = ServerSessionConstantString;
         _typesTypes[1273] = ServerSessionConstantInteger;
         _typesTypes[1271] = ServerSessionConstantLong;
         _typesTypes[2111] = StatisticData;
         _typesTypes[9200] = StatisticDataInt;
         _typesTypes[9792] = StatisticDataBoolean;
         _typesTypes[8387] = StatisticDataShort;
         _typesTypes[5723] = StatisticDataString;
         _typesTypes[7726] = StatisticDataByte;
         _typesTypes[7005] = DebtInformation;
         _typesTypes[6700] = KamaDebtInformation;
      }
      
      public function ProtocolTypeManager()
      {
         super();
      }
      
      public static function getInstance(base:Class, typeId:uint) : *
      {
         var objType:Class = _typesTypes[typeId];
         if(!objType)
         {
            throw new Error("Type with id " + typeId + " is unknown.");
         }
         var obj:* = new objType();
         if(!(obj is base))
         {
            throw new Error("Type " + typeId + " is not a " + base + ".");
         }
         return obj;
      }
      
      public static function register() : void
      {
         StoreDataManager.getInstance().registerClass(new CharacterMinimalPlusLookInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new CharacterBaseInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new PartyMemberInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new PartyMemberArenaInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new PartyInvitationMemberInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new CharacterHardcoreOrEpicInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new CharacterMinimalGuildInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new CharacterMinimalAllianceInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new CharacterMinimalPlusLookAndGradeInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new CharacterBaseInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new PartyMemberInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new PartyMemberArenaInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new PartyInvitationMemberInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new CharacterHardcoreOrEpicInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new EntityDispositionInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new IdentifiedEntityDispositionInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new FightEntityDispositionInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new AbstractSocialGroupInfos(),true,true);
         StoreDataManager.getInstance().registerClass(new BasicGuildInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GuildInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GuildFactSheetInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GuildInsiderFactSheetInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GuildInAllianceInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new AlliancedGuildFactSheetInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new BasicAllianceInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new BasicNamedAllianceInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new AllianceInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new AllianceFactSheetInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GuildVersatileInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GuildInAllianceVersatileInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GuildFactSheetInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GuildInsiderFactSheetInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new AllianceFactSheetInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new PrismSubareaEmptyInfo(),true,true);
         StoreDataManager.getInstance().registerClass(new PrismGeolocalizedInformation(),true,true);
         StoreDataManager.getInstance().registerClass(new PrismInformation(),true,true);
         StoreDataManager.getInstance().registerClass(new AlliancePrismInformation(),true,true);
         StoreDataManager.getInstance().registerClass(new AllianceInsiderPrismInformation(),true,true);
         StoreDataManager.getInstance().registerClass(new CharacterCharacteristic(),true,true);
         StoreDataManager.getInstance().registerClass(new CharacterCharacteristicDetailed(),true,true);
         StoreDataManager.getInstance().registerClass(new CharacterCharacteristicValue(),true,true);
         StoreDataManager.getInstance().registerClass(new FightTeamMemberInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new FightTeamMemberCharacterInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new FightTeamMemberWithAllianceCharacterInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new FightTeamMemberTaxCollectorInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new FightTeamMemberMonsterInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new FightTeamMemberEntityInformation(),true,true);
         StoreDataManager.getInstance().registerClass(new FightTeamInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new FightAllianceTeamInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightCharacteristics(),true,true);
         StoreDataManager.getInstance().registerClass(new FightResultListEntry(),true,true);
         StoreDataManager.getInstance().registerClass(new FightResultFighterListEntry(),true,true);
         StoreDataManager.getInstance().registerClass(new FightResultTaxCollectorListEntry(),true,true);
         StoreDataManager.getInstance().registerClass(new FightResultPlayerListEntry(),true,true);
         StoreDataManager.getInstance().registerClass(new FightResultMutantListEntry(),true,true);
         StoreDataManager.getInstance().registerClass(new FightResultAdditionalData(),true,true);
         StoreDataManager.getInstance().registerClass(new FightResultPvpData(),true,true);
         StoreDataManager.getInstance().registerClass(new FightResultExperienceData(),true,true);
         StoreDataManager.getInstance().registerClass(new AbstractFightDispellableEffect(),true,true);
         StoreDataManager.getInstance().registerClass(new FightTemporaryBoostEffect(),true,true);
         StoreDataManager.getInstance().registerClass(new FightTemporaryBoostStateEffect(),true,true);
         StoreDataManager.getInstance().registerClass(new FightTemporarySpellBoostEffect(),true,true);
         StoreDataManager.getInstance().registerClass(new FightTemporaryBoostWeaponDamagesEffect(),true,true);
         StoreDataManager.getInstance().registerClass(new FightTemporarySpellImmunityEffect(),true,true);
         StoreDataManager.getInstance().registerClass(new FightTriggeredEffect(),true,true);
         StoreDataManager.getInstance().registerClass(new ObjectEffect(),true,true);
         StoreDataManager.getInstance().registerClass(new ObjectEffectInteger(),true,true);
         StoreDataManager.getInstance().registerClass(new ObjectEffectCreature(),true,true);
         StoreDataManager.getInstance().registerClass(new ObjectEffectLadder(),true,true);
         StoreDataManager.getInstance().registerClass(new ObjectEffectMinMax(),true,true);
         StoreDataManager.getInstance().registerClass(new ObjectEffectDuration(),true,true);
         StoreDataManager.getInstance().registerClass(new ObjectEffectString(),true,true);
         StoreDataManager.getInstance().registerClass(new ObjectEffectDice(),true,true);
         StoreDataManager.getInstance().registerClass(new ObjectEffectDate(),true,true);
         StoreDataManager.getInstance().registerClass(new ObjectEffectMount(),true,true);
         StoreDataManager.getInstance().registerClass(new UpdateMountCharacteristic(),true,true);
         StoreDataManager.getInstance().registerClass(new UpdateMountBooleanCharacteristic(),true,true);
         StoreDataManager.getInstance().registerClass(new UpdateMountIntegerCharacteristic(),true,true);
         StoreDataManager.getInstance().registerClass(new Shortcut(),true,true);
         StoreDataManager.getInstance().registerClass(new ShortcutObject(),true,true);
         StoreDataManager.getInstance().registerClass(new ShortcutObjectPreset(),true,true);
         StoreDataManager.getInstance().registerClass(new ShortcutObjectIdolsPreset(),true,true);
         StoreDataManager.getInstance().registerClass(new ShortcutObjectItem(),true,true);
         StoreDataManager.getInstance().registerClass(new ShortcutSpell(),true,true);
         StoreDataManager.getInstance().registerClass(new ShortcutSmiley(),true,true);
         StoreDataManager.getInstance().registerClass(new ShortcutEmote(),true,true);
         StoreDataManager.getInstance().registerClass(new ShortcutEntitiesPreset(),true,true);
         StoreDataManager.getInstance().registerClass(new Idol(),true,true);
         StoreDataManager.getInstance().registerClass(new PartyIdol(),true,true);
         StoreDataManager.getInstance().registerClass(new PartyIdol(),true,true);
         StoreDataManager.getInstance().registerClass(new AchievementAchieved(),true,true);
         StoreDataManager.getInstance().registerClass(new AchievementAchievedRewardable(),true,true);
         StoreDataManager.getInstance().registerClass(new IgnoredInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new IgnoredOnlineInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new FriendInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new FriendOnlineInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new AcquaintanceInformation(),true,true);
         StoreDataManager.getInstance().registerClass(new AcquaintanceOnlineInformation(),true,true);
         StoreDataManager.getInstance().registerClass(new FriendSpouseInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new FriendSpouseOnlineInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new InteractiveElementSkill(),true,true);
         StoreDataManager.getInstance().registerClass(new InteractiveElementNamedSkill(),true,true);
         StoreDataManager.getInstance().registerClass(new InteractiveElement(),true,true);
         StoreDataManager.getInstance().registerClass(new InteractiveElementWithAgeBonus(),true,true);
         StoreDataManager.getInstance().registerClass(new PartyMemberInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new PartyMemberArenaInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new PartyInvitationMemberInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new PartyEntityBaseInformation(),true,true);
         StoreDataManager.getInstance().registerClass(new PartyEntityMemberInformation(),true,true);
         StoreDataManager.getInstance().registerClass(new SkillActionDescription(),true,true);
         StoreDataManager.getInstance().registerClass(new SkillActionDescriptionTimed(),true,true);
         StoreDataManager.getInstance().registerClass(new SkillActionDescriptionCollect(),true,true);
         StoreDataManager.getInstance().registerClass(new SkillActionDescriptionCraft(),true,true);
         StoreDataManager.getInstance().registerClass(new HouseInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new AccountHouseInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new HouseInformationsInside(),true,true);
         StoreDataManager.getInstance().registerClass(new HouseInformationsForGuild(),true,true);
         StoreDataManager.getInstance().registerClass(new HouseOnMapInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new HouseInstanceInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new HouseGuildedInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new PaddockBuyableInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new PaddockGuildedInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameContextActorPositionInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameContextActorInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightFighterInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightAIInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightMonsterInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightMonsterWithAlignmentInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightTaxCollectorInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightFighterNamedInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightCharacterInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightMutantInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightEntityInformation(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayActorInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayNamedActorInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayHumanoidInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayMutantInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayCharacterInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayMountInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayMerchantInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayNpcInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayNpcWithQuestInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayGroupMonsterInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayGroupMonsterWaveInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayTreasureHintInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayTaxCollectorInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayPrismInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayPortalInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameContextActorInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightFighterInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightAIInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightMonsterInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightMonsterWithAlignmentInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightTaxCollectorInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightFighterNamedInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightCharacterInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightMutantInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightEntityInformation(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayActorInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayNamedActorInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayHumanoidInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayMutantInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayCharacterInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayMountInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayMerchantInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayNpcInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayNpcWithQuestInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayGroupMonsterInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayGroupMonsterWaveInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayTreasureHintInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayTaxCollectorInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayPrismInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayPortalInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayActorInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayNamedActorInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayHumanoidInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayMutantInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayCharacterInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayMountInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayMerchantInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayNpcInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayNpcWithQuestInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayGroupMonsterInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayGroupMonsterWaveInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayTreasureHintInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayTaxCollectorInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayPrismInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayPortalInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new HumanInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new HumanOption(),true,true);
         StoreDataManager.getInstance().registerClass(new HumanOptionObjectUse(),true,true);
         StoreDataManager.getInstance().registerClass(new HumanOptionAlliance(),true,true);
         StoreDataManager.getInstance().registerClass(new HumanOptionGuild(),true,true);
         StoreDataManager.getInstance().registerClass(new HumanOptionOrnament(),true,true);
         StoreDataManager.getInstance().registerClass(new HumanOptionEmote(),true,true);
         StoreDataManager.getInstance().registerClass(new HumanOptionTitle(),true,true);
         StoreDataManager.getInstance().registerClass(new HumanOptionSkillUse(),true,true);
         StoreDataManager.getInstance().registerClass(new HumanOptionFollowers(),true,true);
         StoreDataManager.getInstance().registerClass(new TaxCollectorStaticInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new TaxCollectorStaticExtendedInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new TaxCollectorInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new TaxCollectorComplementaryInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new TaxCollectorGuildInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new TaxCollectorLootInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new TaxCollectorWaitingForHelpInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GroupMonsterStaticInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GroupMonsterStaticInformationsWithAlternatives(),true,true);
         StoreDataManager.getInstance().registerClass(new QuestActiveInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new QuestActiveDetailedInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new QuestObjectiveInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new QuestObjectiveInformationsWithCompletion(),true,true);
         StoreDataManager.getInstance().registerClass(new SpawnInformation(),true,true);
         StoreDataManager.getInstance().registerClass(new BaseSpawnMonsterInformation(),true,true);
         StoreDataManager.getInstance().registerClass(new SpawnScaledMonsterInformation(),true,true);
         StoreDataManager.getInstance().registerClass(new SpawnMonsterInformation(),true,true);
         StoreDataManager.getInstance().registerClass(new SpawnCharacterInformation(),true,true);
         StoreDataManager.getInstance().registerClass(new SpawnCompanionInformation(),true,true);
         StoreDataManager.getInstance().registerClass(new GameContextBasicSpawnInformation(),true,true);
         StoreDataManager.getInstance().registerClass(new GameContextSummonsInformation(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightFighterInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightAIInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightMonsterInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightMonsterWithAlignmentInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightTaxCollectorInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightFighterNamedInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightCharacterInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightMutantInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightEntityInformation(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightFighterLightInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightFighterMonsterLightInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightFighterNamedLightInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightFighterTaxCollectorLightInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightFighterEntityLightInformation(),true,true);
         StoreDataManager.getInstance().registerClass(new MapCoordinates(),true,true);
         StoreDataManager.getInstance().registerClass(new MapCoordinatesAndId(),true,true);
         StoreDataManager.getInstance().registerClass(new MapCoordinatesExtended(),true,true);
         StoreDataManager.getInstance().registerClass(new Preset(),true,true);
         StoreDataManager.getInstance().registerClass(new PresetsContainerPreset(),true,true);
         StoreDataManager.getInstance().registerClass(new IconNamedPreset(),true,true);
         StoreDataManager.getInstance().registerClass(new SpellsPreset(),true,true);
         StoreDataManager.getInstance().registerClass(new ForgettableSpellsPreset(),true,true);
         StoreDataManager.getInstance().registerClass(new StatsPreset(),true,true);
         StoreDataManager.getInstance().registerClass(new IdolsPreset(),true,true);
         StoreDataManager.getInstance().registerClass(new EntitiesPreset(),true,true);
         StoreDataManager.getInstance().registerClass(new FullStatsPreset(),true,true);
         StoreDataManager.getInstance().registerClass(new ItemsPreset(),true,true);
         StoreDataManager.getInstance().registerClass(new TreasureHuntStep(),true,true);
         StoreDataManager.getInstance().registerClass(new TreasureHuntStepFollowDirectionToPOI(),true,true);
         StoreDataManager.getInstance().registerClass(new TreasureHuntStepDig(),true,true);
         StoreDataManager.getInstance().registerClass(new TreasureHuntStepFight(),true,true);
         StoreDataManager.getInstance().registerClass(new TreasureHuntStepFollowDirectionToHint(),true,true);
         StoreDataManager.getInstance().registerClass(new TreasureHuntStepFollowDirection(),true,true);
         StoreDataManager.getInstance().registerClass(new AbstractPlayerSearchInformation(),true,true);
         StoreDataManager.getInstance().registerClass(new PlayerSearchTagInformation(),true,true);
         StoreDataManager.getInstance().registerClass(new PlayerSearchCharacterNameInformation(),true,true);
         StoreDataManager.getInstance().registerClass(new PortalInformation(),true,true);
         StoreDataManager.getInstance().registerClass(new BreachBranch(),true,true);
         StoreDataManager.getInstance().registerClass(new ExtendedBreachBranch(),true,true);
         StoreDataManager.getInstance().registerClass(new ExtendedLockedBreachBranch(),true,true);
         StoreDataManager.getInstance().registerClass(new ExtendedBreachBranch(),true,true);
         StoreDataManager.getInstance().registerClass(new ExtendedLockedBreachBranch(),true,true);
         StoreDataManager.getInstance().registerClass(new PlayerStatus(),true,true);
         StoreDataManager.getInstance().registerClass(new PlayerStatusExtended(),true,true);
         StoreDataManager.getInstance().registerClass(new ServerSessionConstant(),true,true);
         StoreDataManager.getInstance().registerClass(new ServerSessionConstantString(),true,true);
         StoreDataManager.getInstance().registerClass(new ServerSessionConstantInteger(),true,true);
         StoreDataManager.getInstance().registerClass(new ServerSessionConstantLong(),true,true);
         StoreDataManager.getInstance().registerClass(new StatisticData(),true,true);
         StoreDataManager.getInstance().registerClass(new StatisticDataInt(),true,true);
         StoreDataManager.getInstance().registerClass(new StatisticDataBoolean(),true,true);
         StoreDataManager.getInstance().registerClass(new StatisticDataShort(),true,true);
         StoreDataManager.getInstance().registerClass(new StatisticDataString(),true,true);
         StoreDataManager.getInstance().registerClass(new StatisticDataByte(),true,true);
         StoreDataManager.getInstance().registerClass(new DebtInformation(),true,true);
         StoreDataManager.getInstance().registerClass(new KamaDebtInformation(),true,true);
      }
   }
}
